### ISSUE TITLE
Potential Improvements

### ISSUE THREAD

**Issue by cchulo** [JustTemmie/steam-presence#30]
Hi, I really like this service you put together. I was initially tempted to fork it and make my own modifications for my own needs, but wanted to check if you were interested in me adding the following features:

- Make the systemd service listen for new processes rather than polling every cycle. While this might not seem as much of a big deal with computers these days, I'd rather want programs to only execute when they are needed. I was thinking of adding something like pyinotification, or even linux's inotification to watch for new processes spawned under /proc
- rather than scrape everything online, some information can be obtained from a processes env if its a steam game. The app id for example can be obtained from it. If you are already listening for processes spawning, you can check to see what environment variables the process has set, grab the steam id, and whatever else.
- build up a cache of previously launched games, why go up online every single time? though the argument could be made against caching if you're running low on storage. Could be something that is configurable.
- Make a GUI for the configuration file, maybe with Qt, and bundle it with flatpak?

Each of these bullet points could be a separate PR to this repo

**Comment by JustTemmie** [comment]
oh I'd gladly accept those as PRs, though some things to keep in mind

- The reason the script searches for information online is so that the script doesn't actually have to run on the same device that you're playing your games on, it's actually really nice for the steam deck; though I don't mind making a toggle for it!

- Don't completely forget about Windows and macOS, meaning if you want to replace the current way the script fetches local processes, please keep the old system as a fallback for those OSes

if refactoring some things into separate files would be easier, go right ahead

thanks for the potential support on the project!

**Comment by JustTemmie** [comment]
haven't heard back from you, i'm closing this issue for now, if you have anything more to say or ask you can gladly re-open it
