### ISSUE TITLE
Changing the RP title to the game name

### ISSUE THREAD

**Issue by TheCheddarCheese** [JustTemmie/steam-presence#48]
I've noticed that with some games the title of the rich presence is the actual name of the game I'm playing, and for others it just says 'a game on steam' and shows the name in the description. Is there a way to set the title to always be the game name?

![image](https://github.com/JustTemmie/steam-presence/assets/124603704/ef6ad2fb-5c37-4db5-bfa1-fb3dd301107d)

![image](https://github.com/JustTemmie/steam-presence/assets/124603704/9bb42998-61cc-474e-8092-833dac04ef43)

(also i just wanted to thank you for making this, my games not appearing properly has been unreasonably bugging me for quite a while now)

**Comment by JustTemmie** [comment]
this isn't possible due to technical limitations, sorry

the discord RPCs all have a  "game ID" associated with them, this is what determines the title of the RPC. Discord's built in detection has "support for certain games" - even I'm unsure what this means they have [this](https://discordapp.com/api/v8/applications/detectable) list of games the client should be able to detect on it's own, this is what Steam Presence uses

tl-dr; discord is stinky and requires every game to be added in their developer dashboard

if you want to, Steam Presence supports you manually adding a game ID for every game you'd want - you might want to do this for games you play a fair bit, you can read how to do that [here](https://github.com/JustTemmie/steam-presence?tab=readme-ov-file#custom-game-ids)

if you have any more questions feel free to ask

**Comment by JustTemmie** [comment]
btw if you can find any games in the aforementioned [list](https://discordapp.com/api/v8/applications/detectable), please tell me what game it is - as the way the script tries finding matching games is a bit rough and could be improved if i had some examples to go off

**Comment by TheCheddarCheese** [comment]
> btw if you can find any games in the aforementioned [list](https://discordapp.com/api/v8/applications/detectable), please tell me what game it is - as the way the script tries finding matching games is a bit rough and could be improved if i had some examples to go off

I'm not sure I understood this correctly, but Touhou 14 is in the list and it's also the example I used as not displaying the name in the title.

**Comment by JustTemmie** [comment]
ah, the problem is that touhou 14 is named "東方輝針城 〜 Double Dealing Character" on steam, and this is the only thing Steam Presence gets informed about, so since discord has called it something else, it just won't detect the right ID 

if you make a file named `customGameIDs.json` within the data/ folder with the name and ID found thru the image
so, this:
```json
{
	"東方輝針城 〜 Double Dealing Character": 505514719885393960
}
```
Steam Presence should be using the correct ID

here's an example of some custom IDs i've setup on my end incase that helps
![image](https://github.com/JustTemmie/steam-presence/assets/47639983/6cf2d0ca-f20c-4a67-9cbf-556d4cf40a1d)
