### ISSUE TITLE
Errors running main.py and installer.sh

### ISSUE THREAD

**Issue by tsundokku** [JustTemmie/steam-presence#9]
When I try to run main.py, it says:
`Forbidden, Access to the steam API has been denied, please verify your steam API key`

I tried resetting my API key a couple times, and I tried using the domains `localhost` and `127.0.0.1`.

I am not sure what to make of this error, as I have used my API key in the past for Steam Idler, and it worked successfully.

As for installer.sh, when I try to run it, it says:
`Error: config.json file not found. Please make sure it exists in the current directory`

This is simply not the case, because I set up the config.json file in the directory in my `Home/steam-presence` directory.
I was not sure if this was because I have VSCodium open, but closing Codium still yields the same results.

Thank you in advance for any support you can provide!

**Comment by JustTemmie** [comment]
the installer looks for specifically "config.json", and not "exampleconfig.json"
that might be your issue, unsure?

**Comment by JustTemmie** [comment]
i mean the dynamic things aren't supported by this, as the steam API literally does not reveal any of the data, this is mostly made so that niche games work.

for the config.json file, where is the installer.sh and the rest of the files located? cause the script tries to install them to the $HOME/steam-presence directory, which might not work if you're already in that folder? i'm honestly quite unsure.

i would believe the steam api key is experiencing the same problem, aka the script is just reading the exampleconfig.json and therefore reading the steam key as "STEAM_API_KEY", and therefore not working.
